meta_title: "The Good Gift"
meta_description: "Offrir un cadeau à plusieurs n’a jamais été aussi simple."
meta_image: "meta.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@_thegoodgift" # indispensable pour les Twitter Cards
